name: 'deploy'

# yamllint disable-line rule:truthy
on:
    push:
        branches:
            - main

jobs:
    deploy-backend:
        runs-on: ubuntu-latest
        steps:
            - name: Cloning repo
              uses: actions/checkout@v2
              with:
                  fetch-depth: 0

            - name: Tailscale
              uses: tailscale/github-action@v1
              with:
                  authkey: ${{ secrets.TAILSCALE_AUTH_KEY }}
            - name: Deploy
              uses: dokku/github-action@master
              with:
                  branch: main
                  git_remote_url: 'ssh://dokku@100.110.108.65:22/backend'
                  ssh_private_key: ${{ secrets.DEPLOY_PRIVATE_KEY }}
    deploy-frontend:
        runs-on: ubuntu-latest
        steps:
            - name: Cloning repo
              uses: actions/checkout@v2
              with:
                  fetch-depth: 0

            - name: Tailscale
              uses: tailscale/github-action@v1
              with:
                  authkey: ${{ secrets.TAILSCALE_AUTH_KEY }}
            - name: Deploy
              uses: dokku/github-action@master
              with:
                  branch: main
                  git_remote_url: 'ssh://dokku@100.110.108.65:22/frontend'
                  ssh_private_key: ${{ secrets.DEPLOY_PRIVATE_KEY }}
    deploy-pi:
        runs-on: ubuntu-latest
        strategy:
            matrix:
                hostname: [100.120.238.39, 100.94.159.89]
            fail-fast: false
        steps:
            - name: Tailscale
              uses: tailscale/github-action@v1
              with:
                  authkey: ${{ secrets.TAILSCALE_AUTH_KEY }}
          
            - name: Run update script
              uses: garygrossgarten/github-action-ssh@release
              with:
                command: /home/pi/app/pi/update.sh
                host: ${{ matrix.hostname }}
                username: pi
                password: ${{ secrets.RASPI_PASSPHRASE }}
